DROP TABLE IF EXISTS CHECKPOINT_DEFININTIONS;
DROP TABLE IF EXISTS DATA_TEST;


CREATE TABLE CHECKPOINT_DEFININTIONS (
  id INT AUTO_INCREMENT  PRIMARY KEY,
   checkpoint VARCHAR(250) NOT NULL,
  camera_definitionId INT NOT NULL

)

CREATE TABLE DATA_TEST (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  bodyid VARCHAR(250) NOT NULL,
  id_checkpoit INT NOT NULL,
  result BOOLEAN NOT NULL
)
